import { z } from 'zod';

export const productQuerySchema = z.object({
  page: z.coerce.number().min(1).default(1),
  limit: z.coerce.number().min(1).max(50).default(12),
  category: z.string().optional(),
  brand: z.string().optional(),
  skinType: z.string().optional(),
  skinConcern: z.string().optional(),
  gender: z.enum(['ALL', 'MEN', 'WOMEN', 'UNISEX']).optional(),
  minPrice: z.coerce.number().min(0).optional(),
  maxPrice: z.coerce.number().min(0).optional(),
  rating: z.coerce.number().min(0).max(5).optional(),
  availability: z.enum(['in_stock', 'all']).optional(),
  sort: z.enum([
    'featured',
    'newest',
    'best_selling',
    'price_asc',
    'price_desc',
    'rating',
    'discount',
  ]).default('featured'),
  search: z.string().optional(),
  isBestSeller: z.enum(['true', 'false']).optional(),
  isFeatured: z.enum(['true', 'false']).optional(),
});

export const createProductSchema = z.object({
  name: z.string().min(2, 'Name is required'),
  brandId: z.string().min(1, 'Brand is required'),
  categoryId: z.string().min(1, 'Category is required'),
  description: z.string().min(10, 'Description must be at least 10 characters'),
  shortDescription: z.string().optional(),
  price: z.number().min(0, 'Price must be positive'),
  compareAtPrice: z.number().min(0).optional().nullable(),
  sku: z.string().min(2, 'SKU is required'),
  stock: z.number().int().min(0, 'Stock cannot be negative'),
  lowStockThreshold: z.number().int().min(0).default(5),
  status: z.enum(['ACTIVE', 'DRAFT', 'ARCHIVED']).default('ACTIVE'),
  gender: z.enum(['ALL', 'MEN', 'WOMEN', 'UNISEX']).default('ALL'),
  weight: z.string().optional().nullable(),
  volume: z.string().optional().nullable(),
  ingredients: z.string().optional().nullable(),
  benefits: z.string().optional().nullable(),
  howToUse: z.string().optional().nullable(),
  countryOfOrigin: z.string().optional().nullable(),
  expiryInformation: z.string().optional().nullable(),
  isFeatured: z.boolean().default(false),
  isBestSeller: z.boolean().default(false),
  isNewArrival: z.boolean().default(false),
  isTrending: z.boolean().default(false),
  badge: z.string().optional().nullable(),
  images: z.array(z.object({
    url: z.string().url(),
    altText: z.string().optional(),
    sortOrder: z.number().default(0),
    isPrimary: z.boolean().default(false),
  })).min(1, 'At least one product image is required'),
  skinTypeIds: z.array(z.string()).optional(),
  skinConcernIds: z.array(z.string()).optional(),
});
